name: Setup Bazel

inputs:
  bazelisk-cache:
    description: Caches Bazelisk downloads based on .bazelversion
    required: false
    default: false
  bazelrc:
    description: Extra contents to write to user .bazelrc
    required: false
    default: ""
  cache-version:
    description: Version of all caches
    required: false
    default: 1
  disk-cache:
    description: Cache actions based on Bazel files
    required: false
    default: false
  external-cache:
    description: Cache external repositories configuration
    required: false
    default: ""
  google-credentials:
    description: Google Cloud account key for remote cache
    required: false
    default: ""
  repository-cache:
    description: Cache repositories based on Bazel files
    required: false
    default: false

runs:
  using: node16
  main: dist/main/index.js
  post: dist/post/index.js
